### PR TITLE
Support for ANSI/US symbol standard

### PR DESCRIPTION
**Pull request by dikkadev**
***This is my first PR, so please lmk if anything I'm doing here is completely off.***

Now you can switch the symbol standard for logic gates! Switch between the 2 standards with display>Toggle Symbols.
You can also set your personal default in General properties. There is also a Note that for the component graphics to change there is the need to restart the program. Changes in a worksheet work smoothly and effectively immediately  (there will probably be some more delay with larger circuits as all the wires have to be recalculated, which is probably the worst-performing part with this)

As it stands the default is to use the newly added symbols, but that could of course be easily changed for a release.
I tried to work closely to your code and make my changes not so obvious.
JsLopotRkZ

### CODE REVIEW

**Comment by kristian** [comment]
Hello @Sett17, your little GIF looks awesome! What a great contribution to the project. Without any review done: Already thanks a lot for all your effort! 👍 Kudos to you.

I am still busy with some personal tasks, at least until Sunday this week. Thus I will be not able to provide you with any feedback to your commit before merging until then, thus please expect some dalay in my review.

Maybe upfront just one thing, which would significantly ease my review: Seems (you? or) your IDE made some significant changes to the code format of the project:

- Most explicit imports have been replaced with wildcard imports:

```
import lc.kra.jds.components.Configurable;
import lc.kra.jds.components.Interactable;
import lc.kra.jds.components.Sociable;
import lc.kra.jds.components.Wire;
```

To:

```
import lc.kra.jds.components.*;
```

- Many tab indentations have been replaced with multi-tab indents.

This makes it super hard to review your change, as literally *every line* in some files was changed. For imports please always let your IDE resolve it to explicit imports in the default order and please try to use the same intendation settings as the project (I think it was generally set to "tab-indentation" for every file). This should significantly reduce the lines changed in this PR.

Another thing I saw by quickly skipping over the files, I still saw some code commented out in your change and also a System.out.println statement. Could you please double check why you added it? Thanks!

Again great change, looking forward getting this merged ASAP! 👍

**Comment by dikkadev** [comment]
I'll get to that!
That should definitely be done for the weekend for you to review!

I think some of the commented-out code was for another addition I'm trying to work on, no promises that it works out ;).
I'll also look through the localization again, probably missed something in there also.

**Comment by kristian** [comment]
Sounds great! 👍 Looking foward to the review! Thanks so much.

**Comment by dikkadev** [comment]
I think it's at least *okay* now. I don't know what's going on with the German translations, but that's the only file that doesn't want to cooperate. If there's anything else I can do, let me know!

 I think the review shouldn't really be such a big hassle as in the beginning.

**Comment by kristian** [comment]
Thanks a lot @Sett17!

I can fix the German translation file if necesarry, no worries!

I think I will get to a review on Sunday afternoon CET. I'll let you know! Thanks again for all your effort!

**Comment by kristian** [comment]
And, yes! 😄 Reviewing +/- 300 lines of code is MUCH easier than the +/- 6000 that have been in the diff before! Thanks again and enjoy your day / night 😄

**Comment by kristian** [comment]
Better late then never I guess... ;) Thanks for the contribution! Squashed with dd6e0b2beee4df2599f1be35fe4bc39b4a868a69 and release 2.2.0.

**Pull request closed without merging**
